CREATE DATABASE IF NOT EXISTS FAMILY_MEMBER;
USE FAMILY_MEMBER;
CREATE TABLE FAMILY_INFORMATION(
ID INT PRIMARY KEY ,
NAME VARCHAR(50),
AGE INT NOT NULL
);
INSERT INTO  FAMILY_INFORMATION
(ID,NAME,AGE)
VALUES
(1,"FATHER:ABDUS_SALAM",55),
(2,"MOTHER:NURUNNAHAR_BEGUM",55),
(3,"BIG_BROTHER:MD BARAT ALI",36),
(4,"MIDDLE_BROTHER:RAJ ALI",25),
(5,"small sister:sumiya ",19);
select * from FAMILY_INFORMATION;

insert into FAMILY_INFORMATION values(6,"Omor_labid",4)
